export const FORMATS = [
  { name: '7"', description: '7-inch single' },
  { name: '10"', description: '10-inch record' },
  { name: '12"', description: '12-inch single or EP' },
  { name: 'LP', description: 'Long play, 12-inch album' },
  { name: 'Box Set', description: 'Multi-record box set' },
  { name: 'Cassette', description: 'Cassette tape' },
  { name: 'CD', description: 'Compact disc' },
]

export const GENRES = [
  'Ambient',
  'Blues',
  'Classical',
  'Country',
  'Electronic',
  'Folk',
  'Funk',
  'Hip-Hop',
  'Jazz',
  'Latin',
  'Metal',
  'Pop',
  'Punk',
  'R&B / Soul',
  'Reggae',
  'Rock',
  'Spoken Word',
  'World',
]
